### ISSUE TITLE
Fatal Error Uncaught Type Error

### ISSUE THREAD

**Issue by alKerim** [telegram-bot-php/durger-king#1]
After clicking on the Order Food Button, the Webview is supposed to open, but instead the following error shows up.
Would be very cool to receive any help or fixes, since this Webview is really cool.
Error:
`Fatal error: Uncaught TypeError: TelegramBot\Telegram::processUpdate(): Argument #1 ($input) must be of type string, bool given, called in /app/vendor/telegram-bot-php/core/src/CrashPad.php on line 117 and defined in /app/vendor/telegram-bot-php/core/src/Telegram.php:141 Stack trace: #0 /app/vendor/telegram-bot-php/core/src/CrashPad.php(117): TelegramBot\Telegram::processUpdate() #1 [internal function]: TelegramBot\CrashPad::TelegramBot\{closure}() #2 {main} thrown in /app/vendor/telegram-bot-php/core/src/Telegram.php on line 141`

Thank you in advance!

**Comment by shahradelahi** [comment]
Please try the update and make sure the `.env` file is updated and the `webhook` is set correctly.

**Comment by alKerim** [comment]
First of all, thanks for the changes and update of dependency!
And secondly, sorry to bother but since I am not an expert in PHP but would still love to run a modified version of DurgerKing... : 
In the readme what do you mean by "server.php" do you mean "service.php" ? 
And also, when I host it now on heroku I only get an "Internal Server Error" and the bot doesn't send the response message to "/start". 
On what platform do you host the bot ?

Would be glad to receive some clarification and/or help on the second question.
Kind regards

**Comment by shahradelahi** [comment]
Thanks for your interest in my project! I'm glad that you like it and want to use it.

I'm not sure what the problem is, if you provide me with the logs I can try to help you.
Also, I updated the project, so you can try the new version.

For deploying the project on Heroku, use this `./bin/heroku-deploy.sh` command, and make sure that you already have Heroku CLI installed.
