### ISSUE TITLE
Dependencies locked...

### ISSUE THREAD

**Issue by vaheedxp** [telegram-bot-php/durger-king#2]
Hi, 
When I install the dependencies, it throw the following errors:

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - shahradelahi/easy-http is locked to version v1.3.0 and an update of this package was not requested.
    - shahradelahi/easy-http v1.3.0 requires ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
  Problem 2
    - utilities-php/auth is locked to version dev-master and an update of this package was not requested.
    - utilities-php/auth dev-master requires ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
  Problem 3
    - utilities-php/common is locked to version dev-master and an update of this package was not requested.
    - utilities-php/common dev-master requires ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
  Problem 4
    - shahradelahi/easy-http v1.3.0 requires ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
    - telegram-bot-php/core v1.0.2 requires shahradelahi/easy-http ~v1.3.0 -> satisfiable by shahradelahi/easy-http[v1.3.0].
    - telegram-bot-php/core is locked to version v1.0.2 and an update of this package was not requested.

**Comment by shahradelahi** [comment]
Hi,
It seems that you have not installed/enable the `pcntl` extension on your system.

For the `telegram-bot-php/core` package, I updated the dependencies, so you can update the project.

If this solution does not work, please provide more information.
